name: Publish to test PyPi.

on:
  push:
    branches: [ pip ]

jobs:
  build-n-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install wheel
        run: python3 -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          verbose: true