# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

name: Publish to PyPi.

on:
  push:
    branches: [pip]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build-n-publish:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install wheel
        run: python3 -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}